export { default as DefaultContent } from "./cob-button.json";
export { default as AccentCoolContent } from "./cob-button~accent-cool.json";
export { default as AccentWarmContent } from "./cob-button~accent-warm.json";
export { default as BaseContent } from "./cob-button~base.json";
export { default as BigContent } from "./cob-button~big.json";
export { default as OutlineContent } from "./cob-button~outline.json";
export { default as OutlineInverseContent } from "./cob-button~outline-inverse.json";
export { default as SecondaryContent } from "./cob-button~secondary.json";
export { default as UnstyledContent } from "./cob-button~unstyled.json";
